Repository YouthCatalyst/calendar, pull requests merged in 2024-08, with the labels that each got.

#5 TECH-120: Create Mentor Registration API (For Google Forms)
  .env.example
  apps/web/pages/api/auth/register-mentor.tsx
  packages/features/auth/signup/handlers/registerUnverifiedMentorHandler.ts
  packages/prisma/zod-utils.ts
  turbo.json
Labels: ❗️ .env changes

#7 TECH-174 feat: get mentor by availability
  apps/web/pages/api/availabilities/mentor-by-availability.ts
Labels: ❗️ migrations

#9 [PR] Booking Endpoints Migration
  apps/web/pages/api/bookings/booking.ts
Labels: ❗️ .env changes, ready-for-e2e
